# Generated by Django 5.2.8 on 2025-11-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('situation', models.CharField(blank=True, max_length=64)),
                ('titles', models.JSONField(blank=True, default=list)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
