# Generated by Django 5.2.8 on 2025-11-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_preview_content_type_item_preview_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
