# Generated by Django 5.2.8 on 2025-11-23 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_source_alter_item_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='item.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
