# Generated by Django 5.2.8 on 2026-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_charactergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactergroup',
            name='titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
