# Generated by Django 5.2.8 on 2026-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_auth_token', models.BinaryField(blank=True, null=True)),
                ('encrypted_ct0', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
