# Generated by Django 5.2.8 on 2026-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_twittercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanbooruTitleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_tag', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
