# Generated by Django 5.2.8 on 2026-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_danboorutitlecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDanbooruLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200, unique=True)),
                ('danbooru_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('resolved_via', models.CharField(blank=True, default='', max_length=32)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('debug_info', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['danbooru_tag'], name='item_charac_danboor_1786a2_idx')],
            },
        ),
    ]
