# Generated by Django 5.2.8 on 2026-09-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_characterdanboorulink'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactergroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='item.charactergroup'),
        ),
    ]
