# Generated by Django 5.2.8 on 2026-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_charactergroup_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialFetchQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'twitter')], default='twitter', max_length=16)),
                ('kind', models.CharField(choices=[('bookmark', 'bookmark'), ('like', 'like')], max_length=16)),
                ('external_id', models.BigIntegerField(unique=True)),
                ('screen_name', models.CharField(blank=True, default='', max_length=64)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('skipped', 'skipped'), ('failed', 'failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TwitterPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
        ),
    ]
