# Generated by Django 5.2.8 on 2026-09-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_socialfetchqueueitem_twitterpollstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialfetchqueueitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
