# Generated by Django 5.2.8 on 2026-09-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_socialfetchqueueitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='character_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='character_regions_image_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
