# Generated by Django 5.2.8 on 2026-09-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_item_character_regions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='character_regions_image_index',
        ),
    ]
