# Generated by Django 5.2.8 on 2026-09-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_remove_item_character_regions_image_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
