# Generated by Django 5.2.8 on 2026-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_item_description_checked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanbooruAliasCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_norm', models.CharField(max_length=200, unique=True)),
                ('resolved_character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
