# Generated by Django 5.2.8 on 2026-09-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_danboorualiascache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAliasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.JSONField(default=list)),
                ('linked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('characters',), name='unique_character_alias_group_characters')],
            },
        ),
    ]
