# Generated by Django 5.2.8 on 2026-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_characteraliasgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='character_regions_ack_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
