# Generated by Django 5.2.8 on 2026-09-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_item_character_regions_ack_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercredential',
            name='encrypted_twid',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
