# Generated by Django 5.2.8 on 2026-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_twittercredential_encrypted_twid'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpollstate',
            name='bookmarks_resume_cursor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='twitterpollstate',
            name='likes_resume_cursor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
