# Generated by Django 5.2.8 on 2026-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_twitterpollstate_bookmarks_resume_cursor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('items_per_tick', models.IntegerField(default=1)),
                ('interval_value', models.IntegerField(default=6)),
                ('interval_unit', models.CharField(choices=[('minutes', '分'), ('hours', '時間'), ('days', '日'), ('weeks', '週')], default='minutes', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
