# Generated by Django 5.2.8 on 2026-09-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_twitterpollstate_bookmarks_resume_cursor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixivCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_phpsessid', models.BinaryField(blank=True, null=True)),
                ('encrypted_user', models.BinaryField(blank=True, null=True)),
                ('encrypted_password', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
