# Generated by Django 5.2.8 on 2026-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_pollersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpollstate',
            name='bookmarks_full_scan_cursor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='twitterpollstate',
            name='likes_full_scan_cursor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
