# Generated by Django 5.2.8 on 2026-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_pollersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_client_id', models.BinaryField(blank=True, null=True)),
                ('encrypted_client_secret', models.BinaryField(blank=True, null=True)),
                ('encrypted_refresh_token', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PixivPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_offset', models.IntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='socialfetchqueueitem',
            name='external_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='socialfetchqueueitem',
            name='platform',
            field=models.CharField(choices=[('twitter', 'twitter'), ('pixiv', 'pixiv')], default='twitter', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='socialfetchqueueitem',
            unique_together={('platform', 'external_id')},
        ),
    ]
