# Generated by Django 5.2.8 on 2026-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_drivecredential_pixivpollstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoipikuCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_lk', models.BinaryField(blank=True, null=True)),
                ('encrypted_jsessionid', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
