# Generated by Django 5.2.8 on 2026-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_poipikucredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollersettings',
            name='backfill_pages_per_tick',
            field=models.IntegerField(default=3),
        ),
    ]
