# Generated by Django 5.2.8 on 2026-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_pollersettings_backfill_pages_per_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollersettings',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('pixiv', 'Pixiv')], default='twitter', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
