# Generated by Django 5.2.8 on 2026-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_split_pixiv_poller_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoipikuPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.CharField(blank=True, default='', max_length=255)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pollersettings',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('pixiv', 'Pixiv'), ('poipiku', 'Poipiku')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='socialfetchqueueitem',
            name='platform',
            field=models.CharField(choices=[('twitter', 'twitter'), ('pixiv', 'pixiv'), ('poipiku', 'poipiku')], default='twitter', max_length=16),
        ),
    ]
