# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_poipikupollstate_alter_pollersettings_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdanboorulink',
            name='conflict_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
