# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_titledanboorulink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanbooruDescriptionLinkCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_hash', models.CharField(max_length=64, unique=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('matched_title_name', models.CharField(blank=True, max_length=255, null=True)),
                ('matched_character_names', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
